
export const metadata = {
    title: "Privacy Policy",
    description: "Our Privacy Policy governs your visit to https://ebitans.com.bd/ and explains how we collect, safeguard and disclose information that results from your use of our Service.",
  };


const Privacy = async ({ params: { locale } }) => {
    const bangla = locale !== "en"
    return (
        <div className='relative z-[1] bg-[#F9F7F6] lg:pt-[85px] pt-[50px]'>
            <div className="sm:h-[40vh] h-[15vh] bg-center bg-[length:100%_100%] flex flex-col gap-4 items-center justify-center bg-[url('https://ebitans.com/Image/cover/eBitans-Web-Bannar1.png')] bg-no-repeat ">
            <h1 className='text-md sm:text-lg md:text-xl lg:text-4xl font-bold text-[#f1593a]'>{bangla ? "eBitans" : "eBitans"}</h1>
                <h1 className=' text-xl sm:text-2xl md:text-4xl lg:text-7xl font-bold text-white'>{bangla ? "প্রাইভেসী পলিসি" : "Privacy Policy"}</h1>
            </div>
            <div className='container px-5 lg:px-10 py-14 text-justify'>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Introduction</h3>
                    <p>Welcome to eBitans.</p>
                    <p>eBitans (“us”, “we”, or “our”) operates at https://ebitans.com/ (here & after referred to as “Service” ).<br />
                        Our Privacy Policy governs your visit to https://ebitans.com/ and explains how we collect, safeguard and disclose information that results from your use of our Service.<br />
                        We use your data to provide and improve Service. By using the Service, you agree to the collection and use of information following this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br />
                        Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitute your agreement with us (“Agreement”).<br />
                    </p>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Definitions</h3>
                    <p><span className='font-bold'>SERVICE:</span> means the https://ebitans.com/ website operated by eBitans.</p>
                    <p><span className='font-bold'>PERSONAL DATA: </span> means data about a living individual who can be identified from those data (or from that and other information either in our possession or likely to come into our possession). </p>
                    <p><span className='font-bold'>USAGE DATA:  </span> is data collected automatically, either generated by the use of Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    <p><span className='font-bold'>DATA CONTROLLER: </span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and how any personal data are or are to be processed. For this Privacy Policy, we are a Data Controller of your data.</p>
                    <p><span className='font-bold'>DATA PROCESSORS (OR SERVICE PROVIDERS): </span>  means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers to process your data more effectively.</p>
                    <p><span className='font-bold'>DATA SUBJECT: </span> is any living individual who is the subject of Personal Data.</p>
                    <p><span className='font-bold'>THE USER: </span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Information Collection and Use</h3>
                    <p>We collect several different types of information for various purposes to provide and improve our service for you.</p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Types of Data Collected</h3>
                    <p>Personal Data</p><br />
                    <p>Personally, identifiable information may include, but is not limited to:</p>
                    <li>Email address.</li>
                    <li>First name and last name.</li>
                    <li>Phone number.</li>
                    <li>Address, Area, City, Country,  ZIP/Postal code,</li><br />
                    <p>We may use your Data to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>

                    <h4 className='font-bold py-2'>Other Data</h4>
                    <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at the place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location, and other data.</p>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Use Of Data</h3>
                    <p><span className='font-bold'>eBitans </span> uses the collected data for various purposes:</p>
                    <li>To provide and maintain our Service;</li>
                    <li>To notify you about changes to our Service;</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so;</li>
                    <li>To provide customer support;</li>
                    <li>To gather analysis or valuable information so that we can improve our Service;</li>
                    <li>To monitor the usage of our Service;</li>
                    <li>To detect, prevent and address technical issues;</li>
                    <li>To fulfill any other purpose for which you provide it;</li>
                    <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                    <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email instructions, etc.;</li>
                    <li>To provide you with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
                    <li>In any other way we may describe when you provide the information;</li>
                    <li>For any other purpose with your consent.</li>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Retention of Data</h3>
                    <p>We will retain your Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br />
                        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.
                    </p>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Transfer of Data</h3>
                    <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.<br />
                        If you are located outside Bangladesh and choose to provide information to us, please note that we transfer the data, including Personal Data, to Bangladesh and process it there.<br />
                        Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br />
                        <span className='font-bold'>eBitans </span> will take all the steps reasonably necessary to ensure that your data is treated securely and following this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Disclosure of Data</h3>
                    <p>We may disclose personal information that we collect, or you provide:</p><br />
                    <li className='font-bold'>Disclosure for Law Enforcement.</li>
                    <p className='pl-5'>Under certain circumstances, we may be required to disclose your Data if required to do so by law or in response to valid requests by public authorities.</p>
                    <li className='font-bold'>Business Transaction.</li>
                    <p className='pl-5'>If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.</p>
                    <li className='font-bold'>Other cases. We may disclose your information also:</li>
                    <div className='pl-5'>
                        <li>To our subsidiaries and affiliates;</li>
                        <li>To contractors, service providers, and other third parties we use to support our business;</li>
                        <li>To fulfill the purpose for which you provide it;</li>
                        <li>To include your company’s logo on our website;</li>
                        <li>For any other purpose disclosed by us when you provide the information;</li>
                        <li>With your consent in any other cases;</li>
                        <li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
                    </div>
                </div>

                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Security of Data</h3>
                    <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect our Personal Data, we cannot guarantee its absolute security.</p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Service Providers</h3>
                    <p>We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used.<br />
                        These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Analytics</h3>
                    <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Payments</h3>
                    <p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).<br />
                        You acknowledge and agree that:<br />
                        We will not store or collect your payment card details. That information is provided directly to our third-party payment processors who use your personal information governed by their Privacy Policy.
                    </p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Links to Other Sites</h3>
                    <p>Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third-party’s site. We strongly advise you to review the Privacy Policy of every visit.<br />
                        We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
                    </p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Children’s Privacy</h3>
                    <p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).
                        We do not knowingly collect personally identifiable information from children under 18. If you become aware that a child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                    </p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Changes to This Privacy Policy</h3>
                    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br />
                        We will inform you via email and/or a prominent notice on our Service before the change becomes effective and update the “effective date” at the top of this Privacy Policy.<br />
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">After Sales Support</h3>
                    <p>We provide full support after the delivery of our service or product if specified in “TOR” or as we consider later.</p>
                </div>
                <div>
                    <h3 className="text-3xl font-bold pt-8 pb-4">Contact Us</h3>
                    <p>If you have any questions about this Privacy Policy, please contact us by<br />
                        <span className='font-bold'>email:</span> support@ebitans.com<br />
                        <span className='font-bold'>Visit Our Office: </span><br />
                        House-39 (4th floor), Road-20, Nikunja-2, Khilkhet, Dhaka-1229
                    </p>
                </div>
                {/* <p>
                    eBitans built the eBitans app as an Ad Supported app. This SERVICE is provided by eBitans at no cost and is intended for use as is.
                    This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.
                    If you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.
                    The terms used in this Privacy Policy have the same meanings as in our <a className='font-bold' href="/terms&conditions" target='_blank'>Terms and Conditions</a>, which are accessible at eBitans unless otherwise defined in this Privacy Policy.</p>

                <h3 className="text-3xl font-bold pt-8 pb-4">Information Collection and Use</h3>

                <p>For a better experience, while using our Service, we may require you to provide us with certain personally identifiable information. The information that we request will be retained by us and used as described in this privacy policy.
                    The app does use third-party services that may collect information used to identify you.
                    Link to the privacy policy of third-party service providers used by the app
                    <ul className="pl-4 pb-4 pt-2 list-disc font-bold"><li><a href="https://policies.google.com/privacy" target='_black'>Google Play Services </a></li></ul>

                    <h3 className="text-3xl font-bold pt-8 pb-4">Log Data</h3>
                    We want to inform you that whenever you use our Service, in a case of an error in the app we collect data and information (through third-party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Cookies</h3>
                    Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.
                    This Service does not use these “cookies” explicitly. However, the app may use third-party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Service Providers</h3>

                    We may employ third-party companies and individuals due to the following reasons:
                    <ul className="pl-4 pb-4 pt-2 list-disc font-bold">
                        <li> To facilitate our Service;</li>
                        <li> To provide the Service on our behalf;</li>
                        <li> To perform Service-related services; or</li>
                        <li> To assist us in analyzing how our Service is used.</li>
                    </ul>
                    We want to inform users of this Service that these third parties have access to their Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Security</h3>
                    We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Links to Other Sites</h3>
                    This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Children’s Privacy</h3>
                    These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13 years of age. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do the necessary actions.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Changes to This Privacy Policy</h3>
                    We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page.
                    This policy is effective as of 06 July 2022.

                    <h3 className="text-3xl font-bold pt-8 pb-4">Contact Us</h3>
                    If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at info@ebitans.com.
                </p> */}
            </div>
        </div>
    )
}

export default Privacy